Solucion_Lab12
cs1000-utec/solucion-labs pull request #3
Opened 2021-12-16 17:06 UTC by Jerimy2021

Muy buenas tardes, profesor esto es la solución al lab12.
Espero su respuesta y cambios de ser necesarios.
Atentamente Sandoval Rivera Jerimy Pierre.

2021-12-18 16:49 UTC, franciscovilchezv requested changes
Incluir este archivo en una carpeta llamada `lab12`. Cambiar el nombre del archivo a `README.md`

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +## 1 Realize una copia
Remover el número 1

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +# Solucion de la parte practica
No olvidar las tildes en `Solución` y `práctica` y en general revisarlas para el resto del documento

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +La solucion de esta parte sera realizada en google colab, por ello ingrese al siguiente enlace, que esta a continuación:
`solución` con tilde

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +### Cuando la copia este lista entre al mismo archivo
Quitar el `###`

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +## 2 Inicializa en la imagen de play de la magia negra
Quitar el `2`

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +### Cuando este listo realize lo msimo con el siguiente, pero cambie el parametro de (k) cluster para que la probabiliad de similitud aumente, esto dependera de usted.
Quitar el `###`

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +## 3 Verifique el resultado en accuracy_score
Quitar el 3

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +### Mientras más se aproxime a 1 más se porcentaje de similitud tendra.
Quitar el `###`

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +## 4 Ejecute esta linea de codigo al final, para clasificar la cedula:
Quitar el 4

2021-12-18 16:49 UTC, franciscovilchezv commented on solucion-lab12.md
> +### Cuando este listo realize lo msimo con el siguiente, pero cambie el parametro de (k) cluster para que la probabiliad de similitud aumente, esto dependera de usted.
No se olvide de las tildes `parámetro`. `probabilidad` esta mal escrito

2021-12-18 16:55 UTC, franciscovilchezv commented on solucion-lab12.md
> +## 4 Ejecute esta linea de codigo al final, para clasificar la cedula:
y el `###`

2021-12-18 16:55 UTC, franciscovilchezv commented on solucion-lab12.md
> +### Mientras más se aproxime a 1 más se porcentaje de similitud tendra.
`tendrá` con tilde

2021-12-18 17:11 UTC, Jerimy2021 commented
Cambios realizados con éxito, por favor puede revisarlo una vez más.

2021-12-18 17:11 UTC, franciscovilchezv requested changes
La carpeta que se llame `lab12` en minúsculas

2021-12-18 17:11 UTC, franciscovilchezv commented on Lab12/README.md
> +##  Inicializa en la imagen de play de la magia negra
Cambiar por:

En la imagen dar `play` a la sección *magia negra*

2021-12-18 17:11 UTC, franciscovilchezv commented on Lab12/README.md
> +Cuando la copia este lista entre al mismo archivo
esté

2021-12-18 17:11 UTC, franciscovilchezv commented on Lab12/README.md
> +Cuando este listo realize lo msimo con el siguiente, pero cambie el parámetro de (k) cluster para que la probabilidad de similitud aumente, esto dependera de usted.
- esté
- mismo
- dependerá

2021-12-18 17:11 UTC, franciscovilchezv commented on Lab12/README.md
> +Mientras más se aproxime a 1 más se porcentaje de similitud tendrá.
Mientras más se aproxime a 1, más porcentaje de similitud tendrá.  (sin `se`)

2021-12-18 17:11 UTC, franciscovilchezv commented on Lab12/README.md
> +##  Ejecute esta linea de codigo al final, para clasificar la cedula:
- línea
- código
- cédula

2021-12-18 17:22 UTC, Jerimy2021 commented
Cambios realizados con éxito.

2021-12-18 17:23 UTC, franciscovilchezv approved these changes
+1 PC1

2021-12-18 17:23 UTC, merged

2021-12-20 17:44 UTC, franciscovilchezv commented
Done